<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

select *
from sales
limit 20

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

20 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16
10,1004,2,2015-01-01,2015-01-01,254117,80,1633,1,8.33,8.33,3.83,CAD,1.16
11,1004,3,2015-01-01,2015-01-01,254117,80,450,1,2297.50,2067.75,761.20,CAD,1.16
12,1005,0,2015-01-01,2015-01-01,1160597,390,1303,10,152.00,152.00,69.90,GBP,0.64
13,1005,1,2015-01-01,2015-01-01,1160597,390,1705,2,4.82,4.82,2.21,GBP,0.64
14,1006,0,2015-01-01,2015-01-01,1895118,480,173,1,71.92,63.29,36.66,USD,1.00
15,1006,1,2015-01-01,2015-01-01,1895118,480,998,5,316.80,310.46,145.68,USD,1.00
16,1007,0,2015-01-01,2015-01-01,1008672,410,55,1,222.00,222.00,73.55,GBP,0.64
17,1007,1,2015-01-01,2015-01-01,1008672,410,1692,4,4.89,4.45,2.49,GBP,0.64
18,1007,2,2015-01-01,2015-01-01,1008672,410,95,1,50.55,50.04,25.77,GBP,0.64
19,1007,3,2015-01-01,2015-01-01,1008672,410,53,1,222.00,222.00,73.55,GBP,0.64

In [7]:
%%sql

select *
from product
order by productkey
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3